#!/bin/bash
#!/usr/bin/bash

echo what is your resource group ?
read MyResourceGroup
echo what is your VNET ?
read MyVNet
echo what is your subnet ?
read MySubnet

Set-Item Env:\SuppressAzurePowerShellBreakingChangeWarnings "true"

subnet_prefix=$(az network vnet subnet show -g $MyResourceGroup -n $MySubnet --vnet-name $MyVNet --query "[addressPrefix]" -o tsv)

BASE_IP=${subnet_prefix%/*}
IP_CIDR=${subnet_prefix#*/}

if [ ${IP_CIDR} -lt 8 ]; then
    echo "Max range is /8."
    exit
fi

IP_MASK=$((0xFFFFFFFF << (32 - ${IP_CIDR})))

IFS=. read a b c d <<<${BASE_IP}

ip=$((($b << 16) + ($c << 8) + $d))

ipstart=$((${ip} & ${IP_MASK}))
ipend=$(((${ipstart} | ~${IP_MASK}) & 0x7FFFFFFF))

seq ${ipstart} ${ipend} | while read i; do
    ip2=$a.$((($i & 0xFF0000) >> 16)).$((($i & 0xFF00) >> 8)).$(($i & 0x00FF))
    availability=$(az network vnet check-ip-address --ip-address $ip2 --resource-group $MyResourceGroup --name $MyVNet --query "[available]" -o tsv)

    if [ "$availability" = "true" ]; 
    then
        echo "IP = $ip2 is avilable"
        echo $ip2 >>$MySubnet.csv
    fi
Set-Item Env:\SuppressAzurePowerShellBreakingChangeWarnings "false"    
done
